services:
  mariadb:
    image: mariadb
    environment:
      - MARIADB_USER=test
      - MARIADB_PASSWORD=test
      - MARIADB_DATABASE=info411.sql
      - MARIADB_ROOT_PASSWORD=root
    ports:
      - 3306:3306
    
  monapache:
    image: avocatmb/monapache
    ports:
      - 80:80
  
  phpmyadmin:
    image: phpmyadmin
    environment:
      - PMA_HOST=mariadb
    ports:
      - 8080:80
  
  monubuntu:
    image: avocatmb/monubuntu

