services:
  mariadb:
    image: mariadb
    environment:
      - MARIADB_USER=${LOGIN_BD}
      - MARIADB_PASSWORD=${PASS_BD}
      - MARIADB_DATABASE=${NOM_BD}
      - MARIADB_ROOT_PASSWORD=${PASS_ROOT_BD}
    ports:
      - 3306:3306
    volumes:
      - ./db_data:/var/lib/mysql
    
  monapache:
    image: avocatmb/monapache
    ports:
      - 127.0.0.1:8082:80
    volumes:
      - .:/var/www/html
    environment:
      - SERVEUR_BD=${SERVEUR_BD}
      - LOGIN_BD=${LOGIN_BD}
      - PASS_BD=${PASS_BD}
      - NOM_BD=${NOM_BD}
  
  phpmyadmin:
    image: phpmyadmin
    environment:
      - PMA_HOST=mariadb
    ports:
      - ${PORT_PHPMYADMIN}:80
  
  monubuntu:
    image: avocatmb/monubuntu

